package com.example.demo.mapper;

import com.example.demo.entity.tb;

public interface tbMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testtable
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testtable
     *
     * @mbggenerated
     */
    int insert(tb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testtable
     *
     * @mbggenerated
     */
    int insertSelective(tb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testtable
     *
     * @mbggenerated
     */
    tb selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testtable
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(tb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testtable
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(tb record);
}