package com.example.demo.entity;

public class tb {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testtable.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testtable.fd
     *
     * @mbggenerated
     */
    private String fd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testtable.id
     *
     * @return the value of testtable.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testtable.id
     *
     * @param id the value for testtable.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testtable.fd
     *
     * @return the value of testtable.fd
     *
     * @mbggenerated
     */
    public String getFd() {
        return fd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testtable.fd
     *
     * @param fd the value for testtable.fd
     *
     * @mbggenerated
     */
    public void setFd(String fd) {
        this.fd = fd == null ? null : fd.trim();
    }
}